name: sync-s3-bucket

on:
  push:
     branches:
       - main
jobs:
  sync-s3-bucket:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: sync-to-buckets
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          aws s3 sync --region us-west-1 --exclude ".*" . s3://troop463website/
